### PR TITLE
Issue #1 - added pause box, timer, and functions 

### PR DESCRIPTION
**Pull request by ryan-broguiere**
For Issue #1 , I added  a Pause box which records the number of times the "pause" button is pressed as well as the time, and it resets when the user presses "clear".

Capture17

I added comments in the style.css file so you can change the CSS of the box around and style it how you like.

For timer.js, I added my own function at the bottom and small helper functions on lines `34`, `111`, and `112`

### CODE REVIEW

**Comment by bellabb111222** [comment]
There s something that's not right.
Screen Shot 2021-12-01 at 6 36 13 PM

**Review by bellabb111222 — CHANGES_REQUESTED** [review]
see comments

**Review by ryan-broguiere — COMMENTED** [review]
added position:relative so that it should stick under the timer, regardless of the screen size

**Review by bellabb111222 — APPROVED** [review]
Well done

**Pull request merged**
