### PR TITLE
added numerical time under clock

### LINKED ISSUE #2: To display numerical time under the CLOCK.
To display numerical time under the corresponding clock.

### PR DESCRIPTION
**Pull request by Kevinla56**

### CODE REVIEW

**Review by bellabb111222 — CHANGES_REQUESTED** [review]
Screen Shot 2021-12-01 at 6 47 53 PM

You wanna try to move the time a little bit down, more closer to the date so it doesn't looks strange.  Plus suppose the time to be display in the format 00:00:00

**Comment by Kevinla56** [comment]
Screen Shot 2021-12-01 at 7 10 11 PM

are the following changes in the screenshot fine?

**Comment by bellabb111222** [comment]
> Screen Shot 2021-12-01 at 7 10 11 PM
> 
> are the following changes in the screenshot fine?

move the time down a little bit to be close to the date.

**Comment by Kevinla56** [comment]
Screen Shot 2021-12-01 at 7 15 43 PM

close enough? or closer?

**Comment by bellabb111222** [comment]
> Screen Shot 2021-12-01 at 7 15 43 PM
> 
> close enough? or closer?

closer?

**Comment by Kevinla56** [comment]
Screen Shot 2021-12-01 at 7 20 36 PM

this as close as i can get it, is it enough?

**Comment by bellabb111222** [comment]
> Screen Shot 2021-12-01 at 7 20 36 PM
> 
> this as close as i can get it, is it enough?

yes thats good

**Comment by Kevinla56** [comment]
alright! changes has been commited

**Review by bellabb111222 — APPROVED** [review]
Well done.

**Pull request merged**
